  
# This is a basic workflow to help you get started with Actions

name: Update and Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  push:
    branches:
      - 'develop'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    
    strategy:
      matrix:
        node-version: [12.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - run: rm -rf node_modules/
    - run: npm cache clean --force

    - run: npm install
      
    - run: npm run deploy --if-present

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: my-artifact
        path: /home/runner/.npm/_logs/*
    # Runs a set of commands using the runners shell
    - name: Comfirm
      run: |
        echo 'Success'
        
